-- HexaScript Constants
-- v1.3

return {

    spawn_aliases = {
        ["airportbus"]="airbus",
        ["ro86alkonost"]="alkonost",
        ["annihilatorstealth"]="annihilator2",
        ["armytrailer"]="armytanker",
        ["astroncustom"]="astron2",
        ["ballerle"]="baller3",
        ["ballerlelwb"]="baller4",
        ["ballerlearmored"]="baller5",
        ["ballerlelwbarmored"]="baller6",
        ["ballerst"]="baller7",
        ["banshee900r"]="banshee2",
        ["barrackssemi"]="barracks2",
        ["bati801"]="bati",
        ["bati801rr"]="bati2",
        ["injection"]="bfinjection",
        ["beejayxl"]="bjxl",
        ["blazerlifeguard"]="blazer2",
        ["hotrodblazer"]="blazer3",
        ["streetblazer"]="blazer4",
        ["blazeraqua"]="blazer5",
        ["atomicblimp"]="blimp",
        ["xeroblimp"]="blimp2",
        ["blimp"]="blimp3",
        ["blistacompact"]="blista2",
        ["gogomonkeyblista"]="blista3",
        ["bodhi"]="bodhi2",
        ["rm10bombushka"]="bombushka",
        ["armoredboxville"]="boxville5",
        ["brickade6x6"]="brickade2",
        ["brioso300"]="brioso2",
        ["brioso300widebody"]="brioso3",
        ["apocalypsebruiser"]="bruiser",
        ["futureshockbruiser"]="bruiser2",
        ["nightmarebruiser"]="bruiser3",
        ["apocalypsebrutus"]="brutus",
        ["futureshockbrutus"]="brutus2",
        ["nightmarebrutus"]="brutus3",
        ["roosevelt"]="btype",
        ["frankenstange"]="btype2",
        ["rooseveltvalor"]="btype3",
        ["buccaneercustom"]="buccaneer2",
        ["buffalos"]="buffalo2",
        ["sprunkbuffalo"]="buffalo3",
        ["buffalostx"]="buffalo4",
        ["dozer"]="bulldozer",
        ["calicogtf"]="calico",
        ["caracara4x4"]="caracara2",
        ["apocalypsecerberus"]="cerberus",
        ["futureshockcerberus"]="cerberus2",
        ["nightmarecerberus"]="cerberus3",
        ["cheetahclassic"]="cheetah2",
        ["chinocustom"]="chino2",
        ["dashound"]="coach",
        ["cognoscenti55"]="cog55",
        ["cognoscenti55armored"]="cog552",
        ["cognoscenticabrio"]="cogcabrio",
        ["cognoscentiarmored"]="cognoscenti2",
        ["comet"]="comet2",
        ["cometretrocustom"]="comet3",
        ["cometsafari"]="comet4",
        ["cometsr"]="comet5",
        ["comets2"]="comet6",
        ["comets2cabrio"]="comet7",
        ["coquetteclassic"]="coquette2",
        ["coquetteblackfin"]="coquette3",
        ["coquetted10"]="coquette4",
        ["cycloneii"]="cyclone2",
        ["apocalypsedeathbike"]="deathbike",
        ["futureshockdeathbike"]="deathbike2",
        ["nightmaredeathbike"]="deathbike3",
        ["devesteeight"]="deveste",
        ["diabolus"]="diablous",
        ["diaboluscustom"]="diablous2",
        ["weaponizeddinghy"]="dinghy5",
        ["duneloader"]="dloader",
        ["pisswasserdominator"]="dominator2",
        ["dominatorgtx"]="dominator3",
        ["apocalypsedominator"]="dominator4",
        ["futureshockdominator"]="dominator5",
        ["nightmaredominator"]="dominator6",
        ["dominatorasp"]="dominator7",
        ["dominatorgtt"]="dominator8",
        ["doublet"]="double",
        ["8fdrafter"]="drafter",
        ["dubsta6x6"]="dubsta3",
        ["dukeodeath"]="dukes2",
        ["beaterdukes"]="dukes3",
        ["dunebuggy"]="dune",
        ["spacedocker"]="dune2",
        ["dunefav"]="dune3",
        ["rampbuggy"]="dune4",
        ["elegyretrocustom"]="elegy",
        ["elegyrh8"]="elegy2",
        ["entityxxr"]="entity2",
        ["entitymt"]="entity3",
        ["hotringeveron"]="everon2",
        ["factioncustom"]="faction2",
        ["factioncustomdonk"]="faction3",
        ["faggiosport"]="faggio",
        ["faggio"]="faggio2",
        ["faggiomod"]="faggio3",
        ["fib"]="fbi",
        ["fcr1000"]="fcr",
        ["fcr1000custom"]="fcr2",
        ["felongt"]="felon2",
        ["feltzer"]="feltzer2",
        ["stirlinggt"]="feltzer3",
        ["firetruck"]="firetruk",
        ["pr4"]="formula",
        ["r88"]="formula2",
        ["freighttrain"]="freight",
        ["futogtx"]="futo2",
        ["redwoodgauntlet"]="gauntlet2",
        ["gauntletclassic"]="gauntlet3",
        ["gauntlethellfire"]="gauntlet4",
        ["gauntletclassiccustom"]="gauntlet5",
        ["gangburrito"]="gburrito",
        ["glendalecustom"]="glendale2",
        ["granger3600lx"]="granger2",
        ["hakuchoudrag"]="hakuchou2",
        ["dockhandler"]="handler",
        ["haulercustom"]="hauler2",
        ["hotringsabre"]="hotring",
        ["howardnx25"]="howard",
        ["fh1hunter"]="hunter",
        ["huntleys"]="huntley",
        ["weaponizedignus"]="ignus2",
        ["apocalypseimpaler"]="impaler2",
        ["futureshockimpaler"]="impaler3",
        ["nightmareimpaler"]="impaler4",
        ["apocalypseimperator"]="imperator",
        ["futureshockimperator"]="imperator2",
        ["nightmareimperator"]="imperator3",
        ["infernusclassic"]="infernus2",
        ["insurgentpickup"]="insurgent",
        ["insurgent"]="insurgent2",
        ["insurgentpickupcustom"]="insurgent3",
        ["issi"]="issi2",
        ["issiclassic"]="issi3",
        ["apocalypseissi"]="issi4",
        ["futureshockissi"]="issi5",
        ["nightmareissi"]="issi6",
        ["issisport"]="issi7",
        ["issirally"]="issi8",
        ["italigtbcustom"]="italigtb2",
        ["jb700w"]="jb7002",
        ["jesterracecar"]="jester2",
        ["jesterclassic"]="jester3",
        ["jesterrr"]="jester4",
        ["journeyii"]="journey2",
        ["blistakanjo"]="kanjo",
        ["tm02khanjali"]="khanjali",
        ["kurumaarmored"]="kuruma2",
        ["landstalkerxl"]="landstalker2",
        ["p996lazer"]="lazer",
        ["re7b"]="le7b",
        ["lifeguard"]="lguard",
        ["turretedlimo"]="limo2",
        ["luxordeluxe"]="luxor2",
        ["mananacustom"]="manana2",
        ["manchezscout"]="manchez2",
        ["manchezscoutc"]="manchez3",
        ["massacroracecar"]="massacro2",
        ["michelligt"]="michelli",
        ["ultralight"]="microlight",
        ["invadeandpersuadetank"]="minitank",
        ["minivancustom"]="minivan2",
        ["v65molotok"]="molotok",
        ["apocalypsesasquatch"]="monster3",
        ["futureshocksasquatch"]="monster4",
        ["nightmaresasquatch"]="monster5",
        ["moonbeamcustom"]="moonbeam2",
        ["lawnmower"]="mower",
        ["mulecustom"]="mule4",
        ["nebulaturbo"]="nebula",
        ["nerocustom"]="nero2",
        ["9f"]="ninef",
        ["9fcabrio"]="ninef2",
        ["p45nokota"]="nokota",
        ["br8"]="openwheel1",
        ["dr1"]="openwheel2",
        ["oppressormkii"]="oppressor2",
        ["oraclexs"]="oracle",
        ["oracle"]="oracle2",
        ["paragonr"]="paragon",
        ["paragonrarmored"]="paragon2",
        ["patriotstretch"]="patriot2",
        ["patriotmilspec"]="patriot3",
        ["kurtz31patrolboat"]="patrolboat",
        ["policeprisonbus"]="pbus",
        ["festivalbus"]="pbus2",
        ["pcj600"]="pcj",
        ["penumbraff"]="penumbra2",
        ["peyotegasser"]="peyote2",
        ["peyotecustom"]="peyote3",
        ["811"]="pfister811",
        ["phantomwedge"]="phantom2",
        ["phantomcustom"]="phantom3",
        ["policecruiser"]="police",
        ["unmarkedcruiser"]="police4",
        ["policebike"]="policeb",
        ["policerancher"]="policeold1",
        ["policeroadcruiser"]="policeold2",
        ["policetransporter"]="policet",
        ["policemaverick"]="polmav",
        ["poundercustom"]="pounder2",
        ["parkranger"]="pranger",
        ["policepredator"]="predator",
        ["primocustom"]="primo2",
        ["x80proto"]="prototipo",
        ["300r"]="r300",
        ["radius"]="radi",
        ["trailer"]="raketrailer",
        ["dune"]="rallytruck",
        ["rapidgtclassic"]="rapidgt3",
        ["rattruck"]="ratloader2",
        ["rustyrebel"]="rebel",
        ["rebel"]="rebel2",
        ["reblagts"]="rebla",
        ["rentalshuttlebus"]="rentalbus",
        ["retinuemkii"]="retinue2",
        ["rhinotank"]="rhino",
        ["policeriot"]="riot",
        ["rcv"]="riot2",
        ["romerohearse"]="romero",
        ["rampantrocket"]="rrocket",
        ["ruiner2000"]="ruiner2",
        ["ruinerzz8"]="ruiner4",
        ["rumpocustom"]="rumpo3",
        ["s80rr"]="s80",
        ["sabreturbo"]="sabregt",
        ["sabreturbocustom"]="sabregt2",
        ["sanchez"]="sanchez2",
        ["sandkingxl"]="sandking",
        ["sandkingswb"]="sandking2",
        ["apocalypsescarab"]="scarab",
        ["futureshockscarab"]="scarab2",
        ["nightmarescarab"]="scarab3",
        ["schafter"]="schafter2",
        ["schafterv12"]="schafter3",
        ["schafterlwb"]="schafter4",
        ["schafterv12armored"]="schafter5",
        ["schafterlwbarmored"]="schafter6",
        ["schlagengt"]="schlagen",
        ["schwartzer"]="schwarzer",
        ["scraptruck"]="scrap",
        ["sparrow"]="seasparrow2",
        ["seminolefrontier"]="seminole2",
        ["sentinelxs"]="sentinel",
        ["sentinel"]="sentinel2",
        ["sentinelclassicwidebody"]="sentinel4",
        ["etr1"]="sheava",
        ["sheriffcruiser"]="sheriff",
        ["sheriffsuv"]="sheriff2",
        ["lostslamvan"]="slamvan2",
        ["slamvancustom"]="slamvan3",
        ["apocalypseslamvan"]="slamvan4",
        ["futureshockslamvan"]="slamvan5",
        ["nightmareslamvan"]="slamvan6",
        ["spectercustom"]="specter2",
        ["clownvan"]="speedo2",
        ["speedocustom"]="speedo4",
        ["stallion"]="stalion",
        ["burgershotstallion"]="stalion2",
        ["lf22starling"]="starling",
        ["b11strikeforce"]="strikeforce",
        ["mallard"]="stunt",
        ["kraken"]="submersible2",
        ["sultanclassic"]="sultan2",
        ["sultanrsclassic"]="sultan3",
        ["superdiamond"]="superd",
        ["supervolitocarbon"]="supervolito2",
        ["surfercustom"]="surfer3",
        ["swiftdeluxe"]="swift2",
        ["tacovan"]="taco",
        ["tahomacoupe"]="tahoma",
        ["tailgaters"]="tailgater2",
        ["drifttampa"]="tampa2",
        ["weaponizedtampa"]="tampa3",
        ["technicalaqua"]="technical2",
        ["technicalcustom"]="technical3",
        ["10f"]="tenf",
        ["10fwidebody"]="tenf2",
        ["terrorbyte"]="terbyte",
        ["tipper"]="tiptruck",
        ["toreroxo"]="torero2",
        ["tornadocustom"]="tornado5",
        ["tornadoratrod"]="tornado6",
        ["fieldmaster"]="tractor2",
        ["mobileoperationscenter"]="trailerlarge",
        ["antiaircrafttrailer"]="trailersmall2",
        ["trashmaster"]="trash",
        ["whippetracebike"]="tribike",
        ["endurexracebike"]="tribike2",
        ["tricyclesracebike"]="tribike3",
        ["desertraid"]="trophytruck2",
        ["troposrallye"]="tropos",
        ["tulipm100"]="tulip2",
        ["turismoclassic"]="turismo2",
        ["utilitytruck"]="utillitruck",
        ["valkyriemod.0"]="valkyrie2",
        ["velum5seater"]="velum2",
        ["verlierer"]="verlierer2",
        ["vetoclassic"]="veto",
        ["vetomodern"]="veto2",
        ["vigerozx"]="vigero2",
        ["virgoclassiccustom"]="virgo2",
        ["virgoclassic"]="virgo3",
        ["rocketvoltic"]="voltic2",
        ["voodoocustom"]="voodoo",
        ["voodoo"]="voodoo2",
        ["warrenerhkr"]="warrener2",
        ["weevilcustom"]="weevil2",
        ["windsordrop"]="windsor2",
        ["xlsarmored"]="xls2",
        ["driftyosemite"]="yosemite2",
        ["yosemiterancher"]="yosemite3",
        ["yougaclassic"]="youga2",
        ["yougaclassic4x4"]="youga3",
        ["yougacustom"]="youga4",
        ["190z"]="z190",
        ["zioncabrio"]="zion2",
        ["zionclassic"]="zion3",
        ["zombiebobber"]="zombiea",
        ["zombiechopper"]="zombieb",
        ["apocalypsezr380"]="zr380",
        ["futureshockzr380"]="zr3802",
        ["nightmarezr380"]="zr3803",
        ["turismoomaggio"]="turismo3",
        ["omaggio"]="turismo3",
        ["cavalcadexl"]="cavalcade3",
        ["hellfire"]="gauntlet4",
        ["hellcat"]="gauntlet4",
        ["veyron"]="adder",
        ["chiron"]="nero",
        ["divo"]="thrax",
        ["f1"]="formula",
        ["asteropegz"]="asterope2",
        ["ballerstd"]="baller8",
        ["dominatorgt"]="dominator9",
        ["impalersz"]="imapler5",
        ["impalerlx"]="imapler6",
        ["policegauntlet"]="polgauntlet",
        ["gauntletinterceptor"]="polgauntlet",
        ["stainerlecruiser"]="police5",
        ["vigerozxconvertible"]="vigero3",
        ["beejayxl"]="bjxl",
        ["oppressormk2"]="oppressor2",
    },

    VEHICLE_COLORS = {
        {
            index=0,
            name="MetallicBlack",
            hex="#0d1116",
            rgb="13, 17, 22",
        },
        {
            index=1,
            name="MetallicGraphiteBlack",
            hex="#1c1d21",
            rgb="28, 29, 33 ",
        },
        {
            index=2,
            name="MetallicBlackSteal",
            hex="#32383d",
            rgb="50, 56, 61 ",
        },
        {
            index=3,
            name="MetallicDarkSilver",
            hex="#454b4f",
            rgb="69, 75, 79 ",
        },
        {
            index=4,
            name="MetallicSilver",
            hex="#999da0",
            rgb="153, 157, 160 ",
        },
        {
            index=5,
            name="MetallicBlueSilver",
            hex="#c2c4c6",
            rgb="194, 196, 198 ",
        },
        {
            index=6,
            name="MetallicSteelGray",
            hex="#979a97",
            rgb="151, 154, 151 ",
        },
        {
            index=7,
            name="MetallicShadowSilver",
            hex="#637380",
            rgb="99, 115, 128 ",
        },
        {
            index=8,
            name="MetallicStoneSilver",
            hex="#63625c",
            rgb="99, 98, 92 ",
        },
        {
            index=9,
            name="MetallicMidnightSilver",
            hex="#3c3f47",
            rgb="60, 63, 71 ",
        },
        {
            index=10,
            name="MetallicGunMetal",
            hex="#444e54",
            rgb="68, 78, 84 ",
        },
        {
            index=11,
            name="MetallicAnthraciteGrey",
            hex="#1d2129",
            rgb="29, 33, 41 ",
        },
        {
            index=12,
            name="MatteBlack",
            hex="#13181f",
            rgb="19, 24, 31 ",
        },
        {
            index=13,
            name="MatteGray",
            hex="#26282a",
            rgb="38, 40, 42 ",
        },
        {
            index=14,
            name="MatteLightGrey",
            hex="#515554",
            rgb="81, 85, 84 ",
        },
        {
            index=15,
            name="UtilBlack",
            hex="#151921",
            rgb="21, 25, 33 ",
        },
        {
            index=16,
            name="UtilBlackPoly",
            hex="#1e2429",
            rgb="30, 36, 41 ",
        },
        {
            index=17,
            name="UtilDarksilver",
            hex="#333a3c",
            rgb="51, 58, 60 ",
        },
        {
            index=18,
            name="UtilSilver",
            hex="#8c9095",
            rgb="140, 144, 149 ",
        },
        {
            index=19,
            name="UtilGunMetal",
            hex="#39434d",
            rgb="57, 67, 77 ",
        },
        {
            index=20,
            name="UtilShadowSilver",
            hex="#506272",
            rgb="80, 98, 114 ",
        },
        {
            index=21,
            name="WornBlack",
            hex="#1e232f",
            rgb="30, 35, 47 ",
        },
        {
            index=22,
            name="WornGraphite",
            hex="#363a3f",
            rgb="54, 58, 63 ",
        },
        {
            index=23,
            name="WornSilverGrey",
            hex="#a0a199",
            rgb="160, 161, 153 ",
        },
        {
            index=24,
            name="WornSilver",
            hex="#d3d3d3",
            rgb="211, 211, 211 ",
        },
        {
            index=25,
            name="WornBlueSilver",
            hex="#b7bfca",
            rgb="183, 191, 202 ",
        },
        {
            index=26,
            name="WornShadowSilver",
            hex="#778794",
            rgb="119, 135, 148 ",
        },
        {
            index=27,
            name="MetallicRed",
            hex="#c00e1a",
            rgb="192, 14, 26 ",
        },
        {
            index=28,
            name="MetallicTorinoRed",
            hex="#da1918",
            rgb="218, 25, 24 ",
        },
        {
            index=29,
            name="MetallicFormulaRed",
            hex="#b6111b",
            rgb="182, 17, 27 ",
        },
        {
            index=30,
            name="MetallicBlazeRed",
            hex="#a51e23",
            rgb="165, 30, 35 ",
        },
        {
            index=31,
            name="MetallicGracefulRed",
            hex="#7b1a22",
            rgb="123, 26, 34 ",
        },
        {
            index=32,
            name="MetallicGarnetRed",
            hex="#8e1b1f",
            rgb="142, 27, 31 ",
        },
        {
            index=33,
            name="MetallicDesertRed",
            hex="#6f1818",
            rgb="111, 24, 24 ",
        },
        {
            index=34,
            name="MetallicCabernetRed",
            hex="#49111d",
            rgb="73, 17, 29 ",
        },
        {
            index=35,
            name="MetallicCandyRed",
            hex="#b60f25",
            rgb="182, 15, 37 ",
        },
        {
            index=36,
            name="MetallicSunriseOrange",
            hex="#d44a17",
            rgb="212, 74, 23 ",
        },
        {
            index=37,
            name="MetallicClassicGold",
            hex="#c2944f",
            rgb="194, 148, 79 ",
        },
        {
            index=38,
            name="MetallicOrange",
            hex="#f78616",
            rgb="247, 134, 22 ",
        },
        {
            index=39,
            name="MatteRed",
            hex="#cf1f21",
            rgb="207, 31, 33 ",
        },
        {
            index=40,
            name="MatteDarkRed",
            hex="#732021",
            rgb="115, 32, 33 ",
        },
        {
            index=41,
            name="MatteOrange",
            hex="#f27d20",
            rgb="242, 125, 32 ",
        },
        {
            index=42,
            name="MatteYellow",
            hex="#ffc91f",
            rgb="255, 201, 31 ",
        },
        {
            index=43,
            name="UtilRed",
            hex="#9c1016",
            rgb="156, 16, 22 ",
        },
        {
            index=44,
            name="UtilBrightRed",
            hex="#de0f18",
            rgb="222, 15, 24 ",
        },
        {
            index=45,
            name="UtilGarnetRed",
            hex="#8f1e17",
            rgb="143, 30, 23 ",
        },
        {
            index=46,
            name="WornRed",
            hex="#a94744",
            rgb="169, 71, 68 ",
        },
        {
            index=47,
            name="WornGoldenRed",
            hex="#b16c51",
            rgb="177, 108, 81 ",
        },
        {
            index=48,
            name="WornDarkRed",
            hex="#371c25",
            rgb="55, 28, 37 ",
        },
        {
            index=49,
            name="MetallicDarkGreen",
            hex="#132428",
            rgb="19, 36, 40 ",
        },
        {
            index=50,
            name="MetallicRacingGreen",
            hex="#122e2b",
            rgb="18, 46, 43 ",
        },
        {
            index=51,
            name="MetallicSeaGreen",
            hex="#12383c",
            rgb="18, 56, 60 ",
        },
        {
            index=52,
            name="MetallicOliveGreen",
            hex="#31423f",
            rgb="49, 66, 63 ",
        },
        {
            index=53,
            name="MetallicGreen",
            hex="#155c2d",
            rgb="21, 92, 45 ",
        },
        {
            index=54,
            name="MetallicGasolineBlueGreen",
            hex="#1b6770",
            rgb="27, 103, 112 ",
        },
        {
            index=55,
            name="MatteLimeGreen",
            hex="#66b81f",
            rgb="102, 184, 31 ",
        },
        {
            index=56,
            name="UtilDarkGreen",
            hex="#22383e",
            rgb="34, 56, 62 ",
        },
        {
            index=57,
            name="UtilGreen",
            hex="#1d5a3f",
            rgb="29, 90, 63 ",
        },
        {
            index=58,
            name="WornDarkGreen",
            hex="#2d423f",
            rgb="45, 66, 63 ",
        },
        {
            index=59,
            name="WornGreen",
            hex="#45594b",
            rgb="69, 89, 75 ",
        },
        {
            index=60,
            name="WornSeaWash",
            hex="#65867f",
            rgb="101, 134, 127 ",
        },
        {
            index=61,
            name="MetallicMidnightBlue",
            hex="#222e46",
            rgb="34, 46, 70 ",
        },
        {
            index=62,
            name="MetallicDarkBlue",
            hex="#233155",
            rgb="35, 49, 85 ",
        },
        {
            index=63,
            name="MetallicSaxonyBlue",
            hex="#304c7e",
            rgb="48, 76, 126 ",
        },
        {
            index=64,
            name="MetallicBlue",
            hex="#47578f",
            rgb="71, 87, 143 ",
        },
        {
            index=65,
            name="MetallicMarinerBlue",
            hex="#637ba7",
            rgb="99, 123, 167 ",
        },
        {
            index=66,
            name="MetallicHarborBlue",
            hex="#394762",
            rgb="57, 71, 98 ",
        },
        {
            index=67,
            name="MetallicDiamondBlue",
            hex="#d6e7f1",
            rgb="214, 231, 241 ",
        },
        {
            index=68,
            name="MetallicSurfBlue",
            hex="#76afbe",
            rgb="118, 175, 190 ",
        },
        {
            index=69,
            name="MetallicNauticalBlue",
            hex="#345e72",
            rgb="52, 94, 114 ",
        },
        {
            index=70,
            name="MetallicBrightBlue",
            hex="#0b9cf1",
            rgb="11, 156, 241 ",
        },
        {
            index=71,
            name="MetallicPurpleBlue",
            hex="#2f2d52",
            rgb="47, 45, 82 ",
        },
        {
            index=72,
            name="MetallicSpinnakerBlue",
            hex="#282c4d",
            rgb="40, 44, 77 ",
        },
        {
            index=73,
            name="MetallicUltraBlue",
            hex="#2354a1",
            rgb="35, 84, 161 ",
        },
        {
            index=74,
            name="MetallicBrightBlue",
            hex="#6ea3c6",
            rgb="110, 163, 198 ",
        },
        {
            index=75,
            name="UtilDarkBlue",
            hex="#112552",
            rgb="17, 37, 82 ",
        },
        {
            index=76,
            name="UtilMidnightBlue",
            hex="#1b203e",
            rgb="27, 32, 62 ",
        },
        {
            index=77,
            name="UtilBlue",
            hex="#275190",
            rgb="39, 81, 144 ",
        },
        {
            index=78,
            name="UtilSeaFoamBlue",
            hex="#608592",
            rgb="96, 133, 146 ",
        },
        {
            index=79,
            name="UtilLightningblue",
            hex="#2446a8",
            rgb="36, 70, 168 ",
        },
        {
            index=80,
            name="UtilMauiBluePoly",
            hex="#4271e1",
            rgb="66, 113, 225 ",
        },
        {
            index=81,
            name="UtilBrightBlue",
            hex="#3b39e0",
            rgb="59, 57, 224 ",
        },
        {
            index=82,
            name="MatteDarkBlue",
            hex="#1f2852",
            rgb="31, 40, 82 ",
        },
        {
            index=83,
            name="MatteBlue",
            hex="#253aa7",
            rgb="37, 58, 167 ",
        },
        {
            index=84,
            name="MatteMidnightBlue",
            hex="#1c3551",
            rgb="28, 53, 81 ",
        },
        {
            index=85,
            name="WornDarkblue",
            hex="#4c5f81",
            rgb="76, 95, 129 ",
        },
        {
            index=86,
            name="WornBlue",
            hex="#58688e",
            rgb="88, 104, 142 ",
        },
        {
            index=87,
            name="WornLightblue",
            hex="#74b5d8",
            rgb="116, 181, 216 ",
        },
        {
            index=88,
            name="MetallicTaxiYellow",
            hex="#ffcf20",
            rgb="255, 207, 32 ",
        },
        {
            index=89,
            name="MetallicRaceYellow",
            hex="#fbe212",
            rgb="251, 226, 18 ",
        },
        {
            index=90,
            name="MetallicBronze",
            hex="#916532",
            rgb="145, 101, 50 ",
        },
        {
            index=91,
            name="MetallicYellowBird",
            hex="#e0e13d",
            rgb="224, 225, 61 ",
        },
        {
            index=92,
            name="MetallicLime",
            hex="#98d223",
            rgb="152, 210, 35 ",
        },
        {
            index=93,
            name="MetallicChampagne",
            hex="#9b8c78",
            rgb="155, 140, 120 ",
        },
        {
            index=94,
            name="MetallicPuebloBeige",
            hex="#503218",
            rgb="80, 50, 24 ",
        },
        {
            index=95,
            name="MetallicDarkIvory",
            hex="#473f2b",
            rgb="71, 63, 43 ",
        },
        {
            index=96,
            name="MetallicChocoBrown",
            hex="#221b19",
            rgb="34, 27, 25 ",
        },
        {
            index=97,
            name="MetallicGoldenBrown",
            hex="#653f23",
            rgb="101, 63, 35 ",
        },
        {
            index=98,
            name="MetallicLightBrown",
            hex="#775c3e",
            rgb="119, 92, 62 ",
        },
        {
            index=99,
            name="MetallicStrawBeige",
            hex="#ac9975",
            rgb="172, 153, 117 ",
        },
        {
            index=100,
            name="MetallicMossBrown",
            hex="#6c6b4b",
            rgb="108, 107, 75 ",
        },
        {
            index=101,
            name="MetallicBistonBrown",
            hex="#402e2b",
            rgb="64, 46, 43 ",
        },
        {
            index=102,
            name="MetallicBeechwood",
            hex="#a4965f",
            rgb="164, 150, 95 ",
        },
        {
            index=103,
            name="MetallicDarkBeechwood",
            hex="#46231a",
            rgb="70, 35, 26 ",
        },
        {
            index=104,
            name="MetallicChocoOrange",
            hex="#752b19",
            rgb="117, 43, 25 ",
        },
        {
            index=105,
            name="MetallicBeachSand",
            hex="#bfae7b",
            rgb="191, 174, 123 ",
        },
        {
            index=106,
            name="MetallicSunBleechedSand",
            hex="#dfd5b2",
            rgb="223, 213, 178 ",
        },
        {
            index=107,
            name="MetallicCream",
            hex="#f7edd5",
            rgb="247, 237, 213 ",
        },
        {
            index=108,
            name="UtilBrown",
            hex="#3a2a1b",
            rgb="58, 42, 27 ",
        },
        {
            index=109,
            name="UtilMediumBrown",
            hex="#785f33",
            rgb="120, 95, 51 ",
        },
        {
            index=110,
            name="UtilLightBrown",
            hex="#b5a079",
            rgb="181, 160, 121 ",
        },
        {
            index=111,
            name="MetallicWhite",
            hex="#fffff6",
            rgb="255, 255, 246 ",
        },
        {
            index=112,
            name="MetallicFrostWhite",
            hex="#eaeaea",
            rgb="234, 234, 234 ",
        },
        {
            index=113,
            name="WornHoneyBeige",
            hex="#b0ab94",
            rgb="176, 171, 148 ",
        },
        {
            index=114,
            name="WornBrown",
            hex="#453831",
            rgb="69, 56, 49 ",
        },
        {
            index=115,
            name="WornDarkBrown",
            hex="#2a282b",
            rgb="42, 40, 43 ",
        },
        {
            index=116,
            name="Wornstrawbeige",
            hex="#726c57",
            rgb="114, 108, 87 ",
        },
        {
            index=117,
            name="BrushedSteel",
            hex="#6a747c",
            rgb="106, 116, 124 ",
        },
        {
            index=118,
            name="BrushedBlacksteel",
            hex="#354158",
            rgb="53, 65, 88 ",
        },
        {
            index=119,
            name="BrushedAluminium",
            hex="#9ba0a8",
            rgb="155, 160, 168 ",
        },
        {
            index=120,
            name="Chrome",
            hex="#5870a1",
            rgb="88, 112, 161 ",
        },
        {
            index=121,
            name="WornOffWhite",
            hex="#eae6de",
            rgb="234, 230, 222 ",
        },
        {
            index=122,
            name="UtilOffWhite",
            hex="#dfddd0",
            rgb="223, 221, 208 ",
        },
        {
            index=123,
            name="WornOrange",
            hex="#f2ad2e",
            rgb="242, 173, 46 ",
        },
        {
            index=124,
            name="WornLightOrange",
            hex="#f9a458",
            rgb="249, 164, 88 ",
        },
        {
            index=125,
            name="MetallicSecuricorGreen",
            hex="#83c566",
            rgb="131, 197, 102 ",
        },
        {
            index=126,
            name="WornTaxiYellow",
            hex="#f1cc40",
            rgb="241, 204, 64 ",
        },
        {
            index=127,
            name="policecarblue",
            hex="#4cc3da",
            rgb="76, 195, 218 ",
        },
        {
            index=128,
            name="MatteGreen",
            hex="#4e6443",
            rgb="78, 100, 67 ",
        },
        {
            index=129,
            name="MatteBrown",
            hex="#bcac8f",
            rgb="188, 172, 143 ",
        },
        {
            index=130,
            name="WornOrange",
            hex="#f8b658",
            rgb="248, 182, 88 ",
        },
        {
            index=131,
            name="MatteWhite",
            hex="#fcf9f1",
            rgb="252, 249, 241 ",
        },
        {
            index=132,
            name="WornWhite",
            hex="#fffffb",
            rgb="255, 255, 251 ",
        },
        {
            index=133,
            name="WornOliveArmyGreen",
            hex="#81844c",
            rgb="129, 132, 76 ",
        },
        {
            index=134,
            name="PureWhite",
            hex="#ffffff",
            rgb="255, 255, 255 ",
        },
        {
            index=135,
            name="HotPink",
            hex="#f21f99",
            rgb="242, 31, 153 ",
        },
        {
            index=136,
            name="Salmonpink",
            hex="#fdd6cd",
            rgb="253, 214, 205 ",
        },
        {
            index=137,
            name="MetallicVermillionPink",
            hex="#df5891",
            rgb="223, 88, 145 ",
        },
        {
            index=138,
            name="Orange",
            hex="#f6ae20",
            rgb="246, 174, 32 ",
        },
        {
            index=139,
            name="Green",
            hex="#b0ee6e",
            rgb="176, 238, 110 ",
        },
        {
            index=140,
            name="Blue",
            hex="#08e9fa",
            rgb="8, 233, 250 ",
        },
        {
            index=141,
            name="MettalicBlackBlue",
            hex="#0a0c17",
            rgb="10, 12, 23 ",
        },
        {
            index=142,
            name="MetallicBlackPurple",
            hex="#0c0d18",
            rgb="12, 13, 24 ",
        },
        {
            index=143,
            name="MetallicBlackRed",
            hex="#0e0d14",
            rgb="14, 13, 20 ",
        },
        {
            index=144,
            name="huntergreen",
            hex="#9f9e8a",
            rgb="159, 158, 138 ",
        },
        {
            index=145,
            name="MetallicPurple",
            hex="#621276",
            rgb="98, 18, 118 ",
        },
        {
            index=146,
            name="MetaillicVDarkBlue",
            hex="#0b1421",
            rgb="11, 20, 33 ",
        },
        {
            index=147,
            name="MODSHOPBLACK1",
            hex="#11141a",
            rgb="17, 20, 26 ",
        },
        {
            index=148,
            name="MattePurple",
            hex="#6b1f7b",
            rgb="107, 31, 123 ",
        },
        {
            index=149,
            name="MatteDarkPurple",
            hex="#1e1d22",
            rgb="30, 29, 34 ",
        },
        {
            index=150,
            name="MetallicLavaRed",
            hex="#bc1917",
            rgb="188, 25, 23 ",
        },
        {
            index=151,
            name="MatteForestGreen",
            hex="#2d362a",
            rgb="45, 54, 42 ",
        },
        {
            index=152,
            name="MatteOliveDrab",
            hex="#696748",
            rgb="105, 103, 72 ",
        },
        {
            index=153,
            name="MatteDesertBrown",
            hex="#7a6c55",
            rgb="122, 108, 85 ",
        },
        {
            index=154,
            name="MatteDesertTan",
            hex="#c3b492",
            rgb="195, 180, 146 ",
        },
        {
            index=155,
            name="MatteFoilageGreen",
            hex="#5a6352",
            rgb="90, 99, 82 ",
        },
        {
            index=156,
            name="DEFAULTALLOYCOLOR",
            hex="#81827f",
            rgb="129, 130, 127 ",
        },
        {
            index=157,
            name="EpsilonBlue",
            hex="#afd6e4",
            rgb="175, 214, 228 ",
        },
        {
            index=158,
            name="PureGold",
            hex="#7a6440",
            rgb="122, 100, 64 ",
        },
        {
            index=159,
            name="BrushedGold",
            hex="#7f6a48",
            rgb="127, 106, 72 ",
        },
    },

    VEHICLE_MAX_OPTIONS = {
        WHEEL_TYPES = 13,
        WINDOW_TINTS = 6,
    },
    
    VEHICLE_CLASSES = {
        COMPACTS = 0,
        SEDANS = 1,
        SUVS = 2,
        COUPES = 3,
        MUSCLE = 4,
        SPORTSCLASSICS = 5,
        SPORTS = 6,
        SUPER = 7,
        MOTORCYCLES = 8,
        OFFROAD = 9,
        INDUSTRIAL = 10,
        UTILITY = 11,
        VANS = 12,
        CYCLES = 13,
        BOATS = 14,
        HELICOPTERS = 15,
        PLANES = 16,
        SERVICE = 17,
        EMERGENCY = 18,
        MILITARY = 19,
        COMMERCIAL = 20,
        TRAINS = 21,
    },

    VEHICLE_WHEEL_TYPES = {
        STOCK = -1,
        SPORT = 0,
        MUSCLE = 1,
        LOWRIDER = 2,
        SUV = 3,
        OFFROAD = 4,
        TUNER = 5,
        BIKE = 6,
        HIGHEND = 7,
        BENNY = 8,
        BENNY2 = 9,
        F1 = 10,
        STREET = 11,
    },

    VEHICLE_PAINT_TYPES = {
        NORMAL = 0,
        METALLIC = 1,
        PEARL = 2,
        MATTE = 3,
        METAL = 4,
        CHROME = 5,
    },

    VEHICLE_MOD_TYPES = {
        MOD_SPOILER = 0,
        MOD_FRONTBUMPER = 1,
        MOD_REARBUMPER = 2,
        MOD_SIDESKIRT = 3,
        MOD_EXHAUST = 4,
        MOD_CHASSIS = 5, --Or roll cage
        MOD_GRILLE = 6,
        MOD_HOOD = 7,
        MOD_FENDER = 8,
        MOD_RIGHTFENDER = 9,
        MOD_ROOF = 10,
        MOD_ENGINE = 11,
        MOD_BRAKES = 12,
        MOD_TRANSMISSION = 13,
        MOD_HORNS = 14,
        MOD_SUSPENSION = 15,
        MOD_ARMOR = 16,
        MOD_UNK17 = 17,
        MOD_TURBO = 18,
        MOD_UNK19 = 19,
        MOD_TIRESMOKE = 20,
        MOD_UNK21 = 21,
        MOD_XENONLIGHTS = 22,
        MOD_FRONTWHEELS = 23,
        MOD_BACKWHEELS = 24, --Bikes only

        -- Benny's
        MOD_PLATEHOLDER = 25,
        MOD_VANITY_PLATES  = 26,
        MOD_TRIM = 27,
        MOD_ORNAMENTS = 28,
        MOD_DASHBOARD = 29,
        MOD_DIAL = 30,
        MOD_DOOR_SPEAKER = 31,
        MOD_SEATS = 32,
        MOD_STEERINGWHEEL = 33,
        MOD_SHIFTER_LEAVERS = 34,
        MOD_PLAQUES = 35,
        MOD_SPEAKERS = 36,
        MOD_TRUNK = 37,
        MOD_HYDRULICS = 38,
        MOD_ENGINE_BLOCK = 39,
        MOD_AIR_FILTER = 40,
        MOD_STRUTS = 41,
        MOD_ARCH_COVER = 42,
        MOD_AERIALS = 43,
        MOD_TRIM = 44,
        MOD_TANK = 45,
        MOD_WINDOWS = 46,
        MOD_UNK47 = 47,
        MOD_LIVERY = 48
    },

    VEHICLE_PLATE_TYPES = {
        MODERN = 0,
        BLACK = 1,
        BLUE = 2,
        CLASSIC = 3,
        EXEMPT = 4,
        YANKTON = 5
    },

    VEHICLE_HEADLIGHT_COLORS = {
        STOCK = -1,
        WHITE = 0,
        BLUE = 1,
        LIGHTBLUE = 2,
        GREEN = 3,
        LIME = 4,
        YELLOW = 5,
        GOLD = 6,
        ORANGE = 7,
        RED = 8,
        PINK = 9,
        HOTPINK = 10,
        PURPLE = 11,
        BLACK = 12
    }

}
